### PR TITLE
fix: fix loan baln rewards calculation

### LINKED ISSUE #91: BALN Rewards for Borrowers is hard-coded
This number should be pulled from the blockchain based on reward allocations. This number is currently hard coded as 10%, but the actual number is 12.5% based on reward allocations. You should be able to use the same APIs used in the BALN Allocation Adjustment Proposal from the Vote tab

### PR DESCRIPTION
**Pull request by hetfly**
close #91

### CODE REVIEW

**Review by parrot9design — APPROVED** [review]
I think this works from a UI perspective? Stats.balanced.network seems to be reporting the right amount of borrower rewards now (12.5%), so it's a little hard to judge.

File: src/queries/index.ts [hunk 1]
```diff
@@ -364,14 +366,31 @@ export const useCollateralInfo = () => {
   };
 };
 
+export function useBalnAllocation() {
```
Comment (octocat512) [inline src/queries/index.ts:369]: I'd like you to use `react-query`. It will reduce and simplify the code. @hetfly

**Review by octocat512 — CHANGES_REQUESTED** [review]

**Comment by octocat512** [comment]
Please resolve the conflicts. @hetfly
